---
- name: Copy docker directory
  copy:
    src: "{{ jenkins_directory }}/docker"
    dest: "{{ jenkins_output_directory }}"

- name: Copy .env
  copy:
    src: "{{ jenkins_directory }}/.env"
    dest: "{{ jenkins_output_directory }}"

- name: Copy docker-compose production configs
  copy:
    src: "{{ jenkins_directory }}/docker-compose.prod.yml"
    dest: "{{ jenkins_output_directory }}"

- name: Copy docker-compose configs
  copy:
    src: "{{ jenkins_directory }}/docker-compose.yml"
    dest: "{{ jenkins_output_directory }}"

- name: Copy Makefile
  copy:
    src: "{{ jenkins_directory }}/Makefile"
    dest: "{{ jenkins_output_directory }}"

- name: Add Certbot hook
  lineinfile:
    path: /etc/letsencrypt/cli.ini
    line: "post-hook = /bin/sh -c 'cd {{ jenkins_output_directory }} && docker-compose restart nginx'"

- name: Run application
  command: make --directory="{{ jenkins_output_directory }}" start-production
