---
- name: Copy files to remote directory
  copy:
    src: "{{ item }}"
    dest: "{{ jenkins_remote_directory }}"
  with_items: "{{ deploy_files }}"

- name: Check /etc/letsencrypt/cli.ini exists
  stat:
    path: /etc/letsencrypt/cli.ini
  register: stat_result

- name: Add Certbot hook
  lineinfile:
    path: /etc/letsencrypt/cli.ini
    line: "post-hook = /bin/sh -c 'cd {{ jenkins_remote_directory }} && docker-compose restart nginx'"
  when: stat_result.stat.exists

- name: Run application
  command: make --directory="{{ jenkins_output_directory }}" start-production
