version: '3.7'
services:
  nginx:
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html:/var/www/html:ro
      - ./docker/production/nginx/conf.d:/etc/nginx/conf.d:ro
