version: '3.7'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - ./docker/development/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - jenkins

  jenkins:
    build:
      context: docker/common/jenkins
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - jenkins-data:/var/jenkins_home

volumes:
  jenkins-data:
