---
- name: Set Certbot package name and versions (Ubuntu < 20.04)
  set_fact:
    certbot_version: 0.31.0-2~deb10u1+ubuntu{{ ansible_distribution_version }}.1+certbot+3
    certbot_nginx_version: 0.31.0-1+ubuntu{{ ansible_distribution_version }}.1+certbot+1
    certbot_nginx_name: python-certbot-nginx
  when: ansible_distribution_version < "20.04"

- name: Add certbot repository
  apt_repository:
    repo: 'ppa:certbot/certbot'
    state: present
  when: ansible_distribution_version < "20.04"

- name: Install Certbot
  apt:
    name: certbot
    state: present
    update_cache: yes

- name: Copy Certbot configuration
  copy:
    src: files/cli.ini
    dest: /etc/letsencrypt/cli.ini
    owner: root
    group: root
    mode: 0644

- name: Remove useless packages
  apt:
    autoclean: yes

- name: Remove useless dependencies
  apt:
    autoremove: yes
